export const langstring={
    eng:{
        Address:'Deliver to Yash - Chandigarh 160036',
        Hello:'Hello',
        Yash:',Yash',
        YourOrder:'Your Orders',
        BuyAgain:"Buy Again",
        YourAccount:"Your Account",
        YourWishlist:"Your Wish List",
        KeepShopping:'Keep Shopping for',
        Edit:'Edit |',
        Browsing:'Browsing',
        SeeAll:'See all',
        ElectricHandel:"Electric Handheld" ,
        Views:"2 viewed",
        IdolsFigures:"Idols & figurines",
        Caramplifiers:"Car amplifiers",
        Mobile:'Mobile',
        Helmets:"Helmets",
        Appliances:'Appliances',
        DealsOfTheDay:'Deals Of The Day',
        Prime:'Prime',
        Fresh:'Fresh',
        Fashion:'Fashion',
        Shoes:'Shoes',
        Bikes:'Bikes',
        Home:'Home',
        Profile:'Profile',
        ShoppingCart:'Shopping Cart',
        Setting:'Setting'
        
    },
    hindi:{
        Address:'यश - चंडीगढ़ 160036 तक पहुंचाएं',
        Hello:'नमस्ते',
        Yash:',यश',
        YourOrder:'तुम्हारे ऑर्डर',
        BuyAgain:"फिर से खरीदें",
        YourAccount:"आपका खाता",
        YourWishlist:"आपकी इच्छा सूची",
        KeepShopping:'खरीदारी करते रहें',
        Edit:'संपादन करना |',
        Browsing:'ब्राउजिंग',
        SeeAll:'सभी देखें',
        ElectricHandel:"इलेक्ट्रिक हैंडहेल्ड" ,
        Views:"2 द्वारा देखा गया",
        IdolsFigures:"मूर्तियाँ और मूर्तियाँ",
        Caramplifiers:"कार एम्पलीफायरों",
        Mobile:'मोबाइल फ़ोन',
        Helmets:"हेलमेट",
        Appliances:'उपकरण',
        DealsOfTheDay:'दिन के सौदे',
        Prime:'प्राइम',
        Fresh:'ताज़ा',
        Fashion:'पहनावा',
        Shoes:'जूते',
        Bikes:'बाइक',
        Home:'होम',
        Profile:'प्रोफ़ाइल',
        ShoppingCart:'शॉपिंग कार्ट',
        Setting:'सेटिंग'
        
        
    }
}
